#------------------------------------------------------------
# Values for this lesson.
# Dummy push to see if our varnish updates are taken...
#------------------------------------------------------------

# Which carpentry is this (swc, dc, lc, or cp)?
# swc: Software Carpentry
# dc: Data Carpentry
# lc: Library Carpentry
# cp: Carpentries (to use for instructor training for instance)
# incubator: The Carpentries Incubator
carpentry: 'incubator'

# Add value for CMS customized "varnish"
varnish: 'cms-opendata-workshop/varnish'

# Overall title for pages.
title: 'ROOT for data analysis' # FIXME

# Date the lesson was created (YYYY-MM-DD, this is empty by default)
created: 2024-07-29 # FIXME

# Comma-separated list of keywords for the lesson
keywords: 'software, data, lesson, CMS' # FIXME

# Life cycle stage of the lesson
# possible values: pre-alpha, alpha, beta, stable
life_cycle: 'stable' # FIXME

# License of the lesson
license: 'CC-BY 4.0'

# Link to the source repository for this lesson
source: 'https://github.com/cms-opendata-workshop/workbench-template-md' # FIXME

# Default branch of your lesson
branch: 'main'

# Who to contact if there are any issues
contact: 'cms-dpoa-coordinator@cern.ch' # FIXME

# Navigation ------------------------------------------------
#
# Use the following menu items to specify the order of
# individual pages in each dropdown section. Leave blank to
# include all pages in the folder.
#
# Example -------------
#
# episodes:
# - introduction.md
# - first-steps.md
#
# learners:
# - setup.md
#
# instructors:
# - instructor-notes.md
#
# profiles:
# - one-learner.md
# - another-learner.md

# Order of episodes in your lesson
episodes: 
- introduction.md
- 02-cpp-hello-world.md
- 03-root-and-cpp-read-and-write.md
- 04-root-and-cpp-fill-a-histogram.md
- 05-going-further-with-pyroot.md
- 06-uproot.md
- 07-awkward.md

# Information for Learners
learners:
- setup.md

# Information for Instructors
instructors: 

# Learner Profiles
profiles: 

# Customisation ---------------------------------------------
#
# This space below is where custom yaml items (e.g. pinning
# sandpaper and varnish versions) should live


